### ISSUE TITLE
Issue when using Bundling & Minification of JS files

### ISSUE THREAD

**Issue by AndyJAllen** [mageplaza/magento-2-social-share#2]
In my test environment, which is  running Magento 2.2.6, this plugin works just fine. However, on my production environment which minifies and merges javascript files, this plugin does not work.

It will fail to load remote source file https://static.addtoany.com/menu/page.js because the minification functionality will change it to 
https://static.addtoany.com/menu/page.min.js     (Notice the .min)

Error looks like the following, as reported in FireFoxes dev console:
The resource from “https://static.addtoany.com/menu/page.min.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

The error isn't exactly correct; the main problem is the url is bad.

Correct me if I'm wrong, but I think the SocialShare plugin needs updated to exclude its off-site url's from the minification functionality of magento; otherwise it won't work with minification enabled.

**Comment by AndyJAllen** [comment]
I did find one solution / work around to this issue.

In the database, navigate to table core_config_data; and see if there is a row with path "dev/js/minify_exclude"....If there isn't you will have to create it. The value for this field is a pipe delimited '|' list of url addresses you want to exclude from being minified...This should be any offsite URL to a file ending in .js.

I created this row with the value "https://static.addtoany.com/menu/page.js" (let the primary key auto increment, plug in the path dev/js/minify_exclude, let other fields default). I recompiled site / deployed static content and now the module is working as expected.

**Comment by Desmond-Mageplaza** [comment]
Hi @AndyJAllen 

At first, thank you for your interest in using Mageplaza Social Share extension.

Since the extension leverage a third party JS library to include the social network channels, we always want to use the latest and most stable version of the JS lib.
This is the reason why we decide to use an external url to deliver the JS content.

I intended to suggest the same solution just like you mentioned in the second response; but you already speak out my mind.
Anyhow, I really hope this minor hurdle does not stop you for using or recommending this extension to others.

Once again, thank you for your fast solution and support.
